nao_ip: 10.0.255.8
nao_port: 9559
trail_port: 5001

face_recog: True
audio_auth: False
audio_authe_user: ninad
vision: False
touch: False

face_recog_api: http://128.205.43.183:PORT/face_recog
transcribe_api: http://128.205.43.183:PORT/transcribe
audio_authen_api: http://128.205.43.183:PORT/audio_recog
main_authen_api: http://128.205.43.183:PORT/complete